# Data Preprocessing Pipeline: The Happy Planet Index

This notebook transforms raw JSON data into a structured and normalized format.

**Input:** Raw JSON dataset  
**Processing:** Type casting, column standardization, missing value handling, validation  
**Output:** Cleaned JSON dataset prepared for database upload

In [4]:
# Importing libraries
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
df = pd.read_json('raw_data\happiness_raw.json') # Check the directory where raw data file is stored

<>:1: SyntaxWarning: invalid escape sequence '\h'
<>:1: SyntaxWarning: invalid escape sequence '\h'
C:\Users\Honor\AppData\Local\Temp\ipykernel_3380\2669937886.py:1: SyntaxWarning: invalid escape sequence '\h'
  df = pd.read_json('raw_data\happiness_raw.json') # Check the directory where raw data file is stored

In [8]:
# glancing at the data
df.head()

,Country,ISO,Continent,HPI_rank_2006,Population_2006,LifeExp_2006,HPI_2006,HPI_rank_2007,Population_2007,LifeExp_2007,...,LifeExp_2019,HPI_2019,HPI_rank_2020,Population_2020,LifeExp_2020,HPI_2020,HPI_rank_2021,Population_2021,LifeExp_2021,HPI_2021
0,Afghanistan,AFG,6,NaN,25442.944,58.684,NaN,NaN,25903.301,59.111,...,63.565,16.936078,146.0,38972.230,62.575,16.455519,144.0,40099.462,61.982,16.210671
1,Albania,ALB,7,NaN,3003.387,76.816,NaN,17.0,2976.084,77.549,...,79.282,46.633530,26.0,2866.849,76.989,48.423285,33.0,2854.710,76.463,46.333546
2,Algeria,DZA,4,NaN,33435.080,72.334,NaN,NaN,33983.827,72.602,...,76.474,43.535362,30.0,43451.666,74.453,47.547291,29.0,44177.969,76.377,47.446084
3,Argentina,ARG,1,12.0,39476.851,75.433,46.402602,23.0,39876.111,75.006,...,77.284,46.700021,40.0,45036.032,75.892,44.896712,41.0,45276.780,75.390,43.792331
4,Armenia,ARM,7,35.0,3026.486,71.987,37.629462,39.0,3004.393,72.327,...,75.439,47.785129,44.0,2805.608,72.173,44.389059,45.0,2790.974,72.043,43.001950

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 67 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Country          149 non-null    object
 1   ISO              149 non-null    object
 2   Continent        149 non-null    int64
 3   HPI_rank_2006    87 non-null     float64
 4   Population_2006  149 non-null    float64
 5   LifeExp_2006     149 non-null    float64
 6   HPI_2006         87 non-null     float64
 7   HPI_rank_2007    117 non-null    float64
 8   Population_2007  149 non-null    float64
 9   LifeExp_2007     149 non-null    float64
 10  HPI_2007         117 non-null    float64
 11  HPI_rank_2008    117 non-null    float64
 12  Population_2008  149 non-null    float64
 13  LifeExp_2008     149 non-null    float64
 14  HPI_2008         117 non-null    float64
 15  HPI_rank_2009    122 non-null    float64
 16  Population_2009  149 non-null    float64
 17  LifeExp_2009     149 non-null    float64
 18  HPI_2009         122 non-null    float64
 19  HPI_rank_2010    126 non-null    float64
 20  Population_2010  149 non-null    float64
 21  LifeExp_2010     149 non-null    float64
 22  HPI_2010         126 non-null    float64
 23  HPI_rank_2011    138 non-null    float64
 24  Population_2011  149 non-null    float64
 25  LifeExp_2011     149 non-null    float64
 26  HPI_2011         138 non-null    float64
 27  HPI_rank_2012    138 non-null    float64
 28  Population_2012  149 non-null    float64
 29  LifeExp_2012     149 non-null    float64
 30  HPI_2012         138 non-null    float64
 31  HPI_rank_2013    138 non-null    float64
 32  Population_2013  149 non-null    float64
 33  LifeExp_2013     149 non-null    float64
 34  HPI_2013         138 non-null    float64
 35  HPI_rank_2014    142 non-null    float64
 36  Population_2014  149 non-null    float64
 37  LifeExp_2014     149 non-null    float64
 38  HPI_2014         142 non-null    float64
 39  HPI_rank_2015    141 non-null    float64
 40  Population_2015  149 non-null    float64
 41  LifeExp_2015     149 non-null    float64
 42  HPI_2015         141 non-null    float64
 43  HPI_rank_2016    140 non-null    float64
 44  Population_2016  149 non-null    float64
 45  LifeExp_2016     149 non-null    float64
 46  HPI_2016         140 non-null    float64
 47  HPI_rank_2017    144 non-null    float64
 48  Population_2017  149 non-null    float64
 49  LifeExp_2017     149 non-null    float64
 50  HPI_2017         144 non-null    float64
 51  HPI_rank_2018    143 non-null    float64
 52  Population_2018  149 non-null    float64
 53  LifeExp_2018     149 non-null    float64
 54  HPI_2018         143 non-null    float64
 55  HPI_rank_2019    140 non-null    float64
 56  Population_2019  149 non-null    float64
 57  LifeExp_2019     149 non-null    float64
 58  HPI_2019         140 non-null    float64
 59  HPI_rank_2020    147 non-null    float64
 60  Population_2020  149 non-null    float64
 61  LifeExp_2020     149 non-null    float64
 62  HPI_2020         147 non-null    float64
 63  HPI_rank_2021    147 non-null    float64
 64  Population_2021  149 non-null    float64
 65  LifeExp_2021     149 non-null    float64
 66  HPI_2021         147 non-null    float64
dtypes: float64(64), int64(1), object(2)
memory usage: 78.1+ KB

In [14]:
df.describe()

,Continent,HPI_rank_2006,Population_2006,LifeExp_2006,HPI_2006,HPI_rank_2007,Population_2007,LifeExp_2007,HPI_2007,HPI_rank_2008,...,LifeExp_2019,HPI_2019,HPI_rank_2020,Population_2020,LifeExp_2020,HPI_2020,HPI_rank_2021,Population_2021,LifeExp_2021,HPI_2021
count,149.000000,87.000000,1.490000e+02,149.000000,87.000000,117.000000,1.490000e+02,149.000000,117.000000,117.000000,...,149.000000,140.000000,147.000000,1.490000e+02,149.000000,147.000000,147.000000,1.490000e+02,149.000000,147.000000
mean,4.718121,44.000000,4.367423e+04,69.087544,33.712331,59.000000,4.421757e+04,69.424483,35.622979,59.000000,...,73.134007,38.999719,74.000000,5.148368e+04,72.363872,38.484358,74.000000,5.192204e+04,71.860423,37.293229
std,2.205891,25.258662,1.474349e+05,9.586623,11.030965,33.919021,1.489415e+05,9.412202,9.969352,33.919021,...,7.734292,9.696958,42.579338,1.674205e+05,7.689131,9.619406,42.579338,1.681928e+05,7.934794,10.002922
min,1.000000,1.000000,2.229230e+02,42.914000,11.195134,1.000000,2.283450e+02,43.123000,8.300212,1.000000,...,52.910000,15.471224,1.000000,3.116850e+02,52.777000,14.338330,1.000000,3.191370e+02,52.525000,13.698084
25%,3.000000,22.500000,4.417560e+03,61.893000,24.465660,30.000000,4.440019e+03,62.543000,28.100339,30.000000,...,66.756000,33.100078,37.500000,5.379839e+03,66.531000,31.872165,37.500000,5.447622e+03,66.072000,30.030470
50%,5.000000,44.000000,1.030482e+04,71.472000,35.605722,59.000000,1.033783e+04,71.652000,37.037761,59.000000,...,74.228000,38.407862,74.000000,1.216172e+04,72.889000,39.606293,74.000000,1.226295e+04,72.438000,38.596764
75%,7.000000,65.500000,2.890561e+04,76.711000,41.807764,88.000000,2.962980e+04,77.017000,42.312437,88.000000,...,79.243000,46.790001,110.500000,3.842837e+04,78.430000,46.319587,110.500000,3.830773e+04,77.728000,45.322870
max,8.000000,87.000000,1.313087e+06,82.376000,64.419974,117.000000,1.321513e+06,82.554000,65.696485,117.000000,...,85.273000,61.735300,147.000000,1.424930e+06,85.197000,57.212000,147.000000,1.425893e+06,85.473000,57.861162

## Recreating long format of the data: performing union of excel sheets

In [16]:
file_4 = "happy_planet.xlsx"
years = range(2006, 2022)

df_list = []

for year in years:
    sheet_name = f"raw_{year}"
    
    df = pd.read_excel(file_4, sheet_name=sheet_name)
    
    df_year = df[[
        "Country",
        "ISO",
        "Continent",
        "HPI rank",
        "Population (thousands)",
        "Life Expectancy (years)",
        "HPI"
    ]]
    
    # добавляем год
    df_year["year"] = year
    
    # переименовываем в нормальный стиль
    df_year = df_year.rename(columns={
        "Country": "country",
        "ISO": "country_code",
        "Continent": "continent",
        "HPI rank": "hpi_rank",
        "Population (thousands)": "population",
        "Life Expectancy (years)": "life_expectancy",
        "HPI": "hpi"
    })
    
    df_list.append(df_year)

C:\Users\Honor\AppData\Local\Temp\ipykernel_3380\3428914421.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_year["year"] = year
C:\Users\Honor\AppData\Local\Temp\ipykernel_3380\3428914421.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_year["year"] = year
C:\Users\Honor\AppData\Local\Temp\ipykernel_3380\3428914421.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_year["year"] = year
C:\Users\Honor\AppData\Local\Temp\ipykernel_3380\3428914421.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_year["year"] = year
C:\Users\Honor\AppData\Local\Temp\ipykernel_3380\3428914421.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_year["year"] = year
C:\Users\Honor\AppData\Local\Temp\ipykernel_3380\3428914421.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_year["year"] = year
C:\Users\Honor\AppData\Local\Temp\ipykernel_3380\3428914421.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_year["year"] = year
C:\Users\Honor\AppData\Local\Temp\ipykernel_3380\3428914421.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_year["year"] = year
C:\Users\Honor\AppData\Local\Temp\ipykernel_3380\3428914421.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_year["year"] = year
C:\Users\Honor\AppData\Local\Temp\ipykernel_3380\3428914421.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_year["year"] = year
C:\Users\Honor\AppData\Local\Temp\ipykernel_3380\3428914421.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_year["year"] = year
C:\Users\Honor\AppData\Local\Temp\ipykernel_3380\3428914421.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_year["year"] = year
C:\Users\Honor\AppData\Local\Temp\ipykernel_3380\3428914421.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_year["year"] = year
C:\Users\Honor\AppData\Local\Temp\ipykernel_3380\3428914421.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_year["year"] = year
C:\Users\Honor\AppData\Local\Temp\ipykernel_3380\3428914421.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_year["year"] = year
C:\Users\Honor\AppData\Local\Temp\ipykernel_3380\3428914421.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_year["year"] = year

In [26]:
# combining
df_final = pd.concat(df_list, ignore_index=True)

In [35]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2384 entries, 0 to 2383
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   country          2384 non-null   object
 1   country_code     2384 non-null   object
 2   continent        2384 non-null   int64
 3   hpi_rank         2127 non-null   float64
 4   population       2384 non-null   float64
 5   life_expectancy  2384 non-null   float64
 6   hpi              2127 non-null   float64
 7   year             2384 non-null   int64
dtypes: float64(4), int64(2), object(2)
memory usage: 149.1+ KB

In [24]:
print(df_final['year'].min())
print(df_final['year'].max())

2006
2021

In [30]:
df_final[df_final['country_code'].isna()]

Empty DataFrame
Columns: [country, country_code, continent, hpi_rank, population, life_expectancy, hpi, year]
Index: []

## adding a common column for manipulations with other tables (table merges): country_name + year
in the current dataset we take fields 'country_code' and 'year' to compose it

In [37]:
df_final["country_year"] = (df_final["country_code"] + df_final["year"].astype(str))

In [39]:
df_final.head()

,country,country_code,continent,hpi_rank,population,life_expectancy,hpi,year,country_year
0,Burundi,BDI,5,NaN,7658.190,53.869,NaN,2006,BDI2006
1,Sudan,SDN,5,NaN,30332.968,60.281,NaN,2006,SDN2006
2,Vanuatu,VUT,8,NaN,222.923,69.462,NaN,2006,VUT2006
3,Sweden,SWE,3,NaN,9104.719,80.832,NaN,2006,SWE2006
4,El Salvador,SLV,1,7.0,6034.436,70.773,49.161381,2006,SLV2006

In [43]:
df_final.to_json(
    "processed_data/hpi_clean.json",
    orient="records",
    indent=4
)